services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/usr/src/app/app
      - ./main.py:/usr/src/app/main.py
    ports:
      - "8000:8000"
    environment:
      AZURE_OPENAI_API_KEY: "${AZURE_OPENAI_API_KEY}"
      AZURE_OPENAI_ENDPOINT: "https://cmpaiservice.openai.azure.com"
      AZURE_OPENAI_DEPLOYMENT: "gpt-4o-mini"
      AZURE_STORAGE_CONNECTION_STRING: "${AZURE_STORAGE_CONNECTION_STRING}"
      AZURE_STORAGE_CONTAINER_NAME: "${AZURE_STORAGE_CONTAINER_NAME}"
      OPENAI_API_KEY: "${OPENAI_API_KEY}"
    command: python main.py